In [1]:
''' 
    # To Create new Enivironment:--
    
    conda create -n env_name python==3.8
    conda activate env_name

'''

^C

Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf

## GPU/CPU Check

In [2]:
tf.__version__

'2.12.0'

In [4]:
tf.keras.__version__

'2.12.0'

In [5]:
variable=tf.Variable([3,3])
if tf.test.is_gpu_available():
    print("GPU")
    print("GPU #0")
    print(var.device.endswith("GPU:0"))
else:
    print("CPU")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU


## Tensor Constant

In [6]:
ineuron=tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
ineuron.numpy()

42

In [9]:
ineuron.dtype

tf.int32

In [10]:
abc=tf.constant("what are you doing")
abc

<tf.Tensor: shape=(), dtype=string, numpy=b'what are you doing'>

In [11]:
abc.numpy()

b'what are you doing'

In [12]:
abc.dtype

tf.string

In [13]:
ineuron1=tf.constant([[4,2],[9,5]])

In [15]:
print(ineuron1)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [18]:
ineuron1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]])>

In [19]:
ineuron1.numpy()

array([[4, 2],
       [9, 5]])

#### Commonly used method is to genetate tf.ones and tf.zeroes

In [23]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [24]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [27]:
print(tf.zeros(shape=(4,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [28]:
tf.zeros(shape=(4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [30]:
const2 =tf.constant([[3,4,5],[5,6,7]]);
const3= tf.constant([[1,2,3],[4,5,6]])
result=tf.add(const2,const3)
print(result)

tf.Tensor(
[[ 4  6  8]
 [ 9 11 13]], shape=(2, 3), dtype=int32)


### Random Constant

In [31]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5402462 , -0.9209861 ],
       [ 0.35840383,  1.5727737 ]], dtype=float32)>

In [34]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 8],
       [7, 7]])>

### Declaring Variable

In [3]:
var0=24 # Python variable
var1=tf.Variable(36)
var2=tf.Variable([ [ [1,2,3], [4,5,6], [7,8,9]]])

var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=36>,
 <tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])>)

In [6]:
var3=tf.Variable([ [[0.,1.,2.], [3.,4.,5]], [[6.,7.,8.],[9.,10.,11]]])
var3

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

#### To Reassign a variable

In [7]:
var_reassign=tf.Variable(56)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=56>

In [8]:
var_reassign.assign(74)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=74>

In [9]:
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=74>

In [12]:
initial_value=tf.random.normal(shape=(2,2))
a=tf.Variable(initial_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.73259133,  0.45043862],
       [-0.95770437,  0.643987  ]], dtype=float32)>

In [14]:
tensorr=tf.Variable([ [ [1,1],[2,2],[3,3] ], [ [4,4],[5,5],[6,6] ], [ [7,7],[8,8],[9,9] ] ])
tensorr

<tf.Variable 'Variable:0' shape=(3, 3, 2) dtype=int32, numpy=
array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8],
        [9, 9]]])>

In [37]:
tensorr1=tf.Variable([ [ [1.,1,1,1],[2,2,2,2],[3,3,3,3] ], [ [4,4,4,4],[5,5,5,5],[6,6,6,6] ]])
tensorr1

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]]], dtype=float32)>

In [20]:
tensorr2=tf.reshape(tensorr1,[2,12])
tensorr2

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3],
       [4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6]])>

In [23]:
tensorr1

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])>

In [24]:
tensorr1.numpy()

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])

In [27]:
tensorr1[1,0,2].numpy()

4

In [28]:
tenssor_size=tf.size(input=tensorr)
tenssor_size

<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [29]:
tenssor_size=tf.size(input=tensorr).numpy()
tenssor_size

18

### Mathematical Operation

In [30]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
d=tf.square(c)
e=tf.exp(c)

print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.5185343  -0.5458327 ]
 [ 0.52655137 -0.46319637]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.26887783 0.29793334]
 [0.27725634 0.21455087]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.6795641  0.5793592 ]
 [1.6930834  0.62926906]], shape=(2, 2), dtype=float32)


In [31]:
a=tf.Variable(3)
b=tf.Variable(4)
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [32]:
a=tf.Variable([2,3])
b=tf.Variable([4,5])
c=a+b
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8])>

### Matrix Multilplication

In [33]:
matrix_u=tf.constant([[1,2,3]])
matrix_v=tf.constant([[4,5,6]])
tf.matmul(matrix_u,tf.transpose(matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]])>

### Changing the Datatype

In [38]:
tensorr1

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]]], dtype=float32)>

In [39]:
# Change the dtype 
tf.cast(tensorr1,dtype=tf.int32)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])>

In [43]:
j=tf.cast(tf.constant(4,6,3),dtype=tf.int32)
j

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 4, 4])>

In [44]:
id(j)

1614546652496

## Ragged Tensor

In [46]:
# Here we can give Different different Dimension of the dataset:
ragged=tf.ragged.constant([[1,2,3],[],[4,1,2,3],[1,2]])
ragged

<tf.RaggedTensor [[1, 2, 3], [], [4, 1, 2, 3], [1, 2]]>

In [55]:
print(ragged[0,:1])
print(ragged[2,:])

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([4 1 2 3], shape=(4,), dtype=int32)


### Mean median max

In [56]:
number=tf.constant([ [8.,9.], [1.,2.]])
number

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 9.],
       [1., 2.]], dtype=float32)>

In [57]:
tf.reduce_mean(input_tensor=number)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [58]:
tf.reduce_max(input_tensor=number)

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [59]:
tf.reduce_min(input_tensor=number)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [64]:
number

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 9.],
       [1., 2.]], dtype=float32)>

In [62]:
tf.reduce_mean(input_tensor=number,axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

In [63]:
tf.reduce_mean(input_tensor=number,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

In [87]:
tf.random.set_seed(5)
tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=5,name=None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 6.9702053, 12.397479 ],
       [10.290582 ,  8.864535 ],
       [ 8.798839 , 13.825927 ]], dtype=float32)>

In [89]:
dice_1=tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice_2=tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))

dice_sum=dice_1+dice_2
final_matrix=tf.concat(values=[dice_1,dice_2,dice_sum],axis=1)
print(final_matrix)

tf.Tensor(
[[ 4  2  6]
 [ 1  2  3]
 [ 6  2  8]
 [ 5  1  6]
 [ 6  6 12]
 [ 1  5  6]
 [ 4  6 10]
 [ 1  4  5]
 [ 4  6 10]
 [ 5  3  8]], shape=(10, 3), dtype=int32)


### CheckPoint`

In [91]:
variable_1=tf.Variable([ [5,6,7,8] , [9,10,11,12]])
checkpoint(tf.train.Checkpoint(var=variable_1))
savepath=checkpoint.save('')
variable_1.assign([ [0,0,0,0] , [0,0,0,0]])

variable_1
checkpoint.restore(savepath)
print(variable_1)

NameError: name 'checkpoint' is not defined

## Gradient Tape

In [118]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c=tf.sqrt(tf.square(a) + tf.square(b))
    dc_da=tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.47773024 -0.7376062 ]
 [ 0.15465102  0.17718387]], shape=(2, 2), dtype=float32)


In [122]:
a=tf.Variable(a)
with tf.GradientTape() as tape:
    c=tf.sqrt(tf.square(a) + tf.square(b))
    dc_da=tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.47773024 -0.7376062 ]
 [ 0.15465102  0.17718387]], shape=(2, 2), dtype=float32)


# Using The DataSet

In [125]:
mnist_data=tf.keras.datasets.mnist
mnist_data.load_data()

11490434/11490434 [==============================] - 40s 4us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [126]:
(train_x,train_y),(test_x,test_y)=mnist_data.load_data()

In [134]:
print("Train Size: ",train_x.shape)
print("Test Size: ",test_x.shape)

Train Size:  (60000, 28, 28)
Test Size:  (10000, 28, 28)


In [135]:
epochs=10
batch_size=32

In [136]:
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64), tf.cast(test_y,tf.int64)

## Building The Model

In [143]:
mnistmodel_1=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(), # input layer
    tf.keras.layers.Dense(512,activation=tf.nn.relu), # hidden layer
    tf.keras.layers.Dense(60,activation=tf.nn.tanh),  # 2nd hidden layer
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10,activation=tf.nn.softmax) # output layer
])

### compile the model with optimiser

In [146]:
optimiser=tf.keras.optimizers.Adam()
mnistmodel_1.compile(optimizer=optimiser,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [147]:
# Fitting The model:
mnistmodel_1.fit(train_x,train_y,batch_size=32,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 17s 9ms/step - loss: 0.2075 - accuracy: 0.9396
Epoch 2/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.0865 - accuracy: 0.9735
Epoch 3/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0597 - accuracy: 0.9816
Epoch 4/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0452 - accuracy: 0.9856
Epoch 5/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.0360 - accuracy: 0.9887


In [148]:
# Evaluting the model (testing)
mnistmodel_1.evaluate(test_x,test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.0632 - accuracy: 0.9819


[0.06317757070064545, 0.9818999767303467]

In [149]:
# Prediction:
mnistmodel_1.predict(test_x)

313/313 [==============================] - 1s 2ms/step


array([[3.5977715e-07, 2.1318876e-05, 9.4483739e-06, ..., 9.9990833e-01,
        2.0533969e-06, 1.0765631e-05],
       [4.9399046e-06, 1.8237975e-05, 9.9996173e-01, ..., 1.2180498e-06,
        3.9730971e-06, 2.7254867e-08],
       [2.1514020e-06, 9.9992740e-01, 4.6548257e-06, ..., 3.1685555e-05,
        5.3463555e-06, 7.1009026e-08],
       ...,
       [3.7423789e-07, 4.2725637e-06, 2.6277641e-07, ..., 7.2999196e-06,
        2.2991653e-06, 3.3012839e-05],
       [1.6979836e-06, 8.2297743e-07, 1.9362874e-07, ..., 9.7549787e-07,
        3.4342194e-04, 2.0663958e-06],
       [1.2674394e-05, 7.5065691e-07, 7.0374899e-06, ..., 3.7873786e-08,
        1.5306859e-06, 1.3589018e-07]], dtype=float32)

In [152]:
mnistmodel_1.predict_classes(test_x) ## this function is removed in the new verrsiom

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [154]:
mnistmodel_2=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(744,activation=tf.nn.relu),
    tf.keras.layers.Dense(102,activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(40,activation=tf.nn.tanh),
    tf.keras.layers.Dense(10,activation=tf.nn.softmax) # Output layer
])

In [155]:
mnistmodel_2.compile(optimizer=tf.keras.optimizers.Adam(),loss='sparse_categorical_crossentropy',
                     metrics=["accuracy"])

In [156]:
mnistmodel_2.fit(train_x,train_y,batch_size=64,epochs=4)

Epoch 1/4
938/938 [==============================] - 13s 13ms/step - loss: 0.2385 - accuracy: 0.9331
Epoch 2/4
938/938 [==============================] - 11s 12ms/step - loss: 0.0957 - accuracy: 0.9714
Epoch 3/4
938/938 [==============================] - 12s 13ms/step - loss: 0.0666 - accuracy: 0.9793
Epoch 4/4
938/938 [==============================] - 13s 14ms/step - loss: 0.0491 - accuracy: 0.9852


In [157]:
mnistmodel_2.evaluate(test_x,test_y)

313/313 [==============================] - 1s 3ms/step - loss: 0.0826 - accuracy: 0.9760


[0.08262426406145096, 0.9760000109672546]

## To Save mmodel

In [160]:
tf.saved_model.save(mnistmodel_2,export_dir="C:/Users/win11/iNeuron_Classes/2_Recorded_classes_ineuron/18. Deep Learning")

INFO:tensorflow:Assets written to: C:/Users/win11/iNeuron_Classes/2_Recorded_classes_ineuron/18. Deep Learning\assets


INFO:tensorflow:Assets written to: C:/Users/win11/iNeuron_Classes/2_Recorded_classes_ineuron/18. Deep Learning\assets
